# -*- coding: utf-8 -*-
"""231011 자료구조-1주차-알고리즘 기초.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EfForGuWW2w9wYTXhx-rR3DrOZ71RLWM

# 01-1. 알고리즘이란?

## 실습 1-14. 반복 과정에서 조건 판단하기 3
"""

# *를 n개 출력하되 w개마다 줄바꿈하기1

print('*를 출력합니다.')
n = int(input('몇 개를 출력할까요?: '))
w = int(input('몇 개마다 줄바꿈할까요?: '))

for i in range(n):
  print('*', end='') #*을 출력 후 더이상 나누어 지지 않을 때, 조건 2 수행
  if i % w == w - 1: #조건2 : (n/w 한 나머지) == (w-1)
                     #컴퓨터는 숫자를 0부터 셈
    print()

if n % w == 0: #'if n % w :' 와 표현 동일(조건 True)
               #for 문 수행과 동시에 조건 판단
               # 조건1 : *를 출력 하되, 나누어지는 수일 때 띄어쓰기 실행

  print()

# <결과 리뷰>
#(14, 5) : '*' 5개 2줄, 4개 1줄
#(31, 11) :  '*' 11개 2줄, 9개 1줄
#(56, 15) : '*' 15개 3줄, 11개 1줄
#(79, 20) : '*' 20개 3줄, 19개 1줄
#(21, 1) : '*' 21개 1줄 , 0개 0줄
#(3, 10) : '*' 3개 0줄
#(0, 10) : X (0으로 수렴)
#(10, 0) : error (무한대로 발산)
